sudo apt-get install update 
sudo apt-get install g++ 
sudo apt-get install libncurses5-dev 
sudo apt-get install zlib1g-dev 
sudo apt-get install bison 
sudo apt-get install flex 
sudo apt-get install unzip 
sudo apt-get install autoconf 
sudo apt-get install gawk 
sudo apt-get install make 
sudo apt-get install gettext 
sudo apt-get install gcc 
sudo apt-get install binutils 
sudo apt-get install patch 
sudo apt-get install bzip2 
sudo apt-get install libz-dev 
sudo apt-get install asciidoc 
sudo apt-get install subversion
sudo apt-get install sphinxsearch
sudo apt-get install libtool
sudo apt-get install sphinx-common
